### PR TITLE
Mods Screen: Fixed Crash

### PR DESCRIPTION
**Pull request by danterusdev**
On systems that don't support BROWSE, there is a crash when the client attempts to show the blocked mods page for a server. If you add notifications in the future you could send a notification letting the user know that the browse action could not be done.

### CODE REVIEW

**Comment by TheKodeToad** [comment]
What happens if you click on a link in the electron launcher?

**Comment by danterusdev** [comment]
Those links in the launcher do work.

**Comment by danterusdev** [comment]
Update: I found an alternative method of browsing (using lwjgl) that does open the webpage for me.

**Comment by TheKodeToad** [comment]
This new method does not respect the default browser (at least for me). It opens in Epiphany (and on Windows, probably Microsoft Edge, which is even more impolite) despite my default browser being Firefox. It may be better to create a method in Utils that passes a message to the launcher through stderr.

**Comment by TheKodeToad** [comment]
Thank you, and happy new year!

**Comment by TheKodeToad** [comment]
@danterusdev Are you fine with me relicensing the project with GPL v3? You are the only other contributor other than me. It seems that the code was previously violating the GPL license, since it uses ReplayMod code, and some code from Hyperium.

**Pull request merged**
