### PR TITLE
Refactored ToggleSprintKeybinding logic into abstract ToggledKeybinding

### PR DESCRIPTION
**Pull request by TatoExp**
Refactored ToggleSprintKeybinding to use this abstract ToggleKeybinding to reduce duplicate code when implementing #39

### CODE REVIEW

**Comment by TheKodeToad** [comment]
Hi, thanks for this! Toggle sneak is a feature I've been wanting to implement for a long while.

Please can you switch to using the dev/1.9.0 branch? I've switched the target branch, but I don't think the conflicts can be fixed unless you make some changes.

**Comment by TheKodeToad** [comment]
It looks like there is still a conflict remaining.

**Comment by TatoExp** [comment]
@TheKodeToad Yeah I accidentally missed a marker, I've also formatted the files. Although I'm using intellij so I'm not sure if it formatted how you want it to be.

**Comment by TheKodeToad** [comment]
I can manually fix the formatting (it's using spaces).

**Comment by TheKodeToad** [comment]
Thank you! The build error is fine for now. Although you may have some issues running code with errors in IntelliJ (Eclipse lets you).

Until I port the quick play UI to use NanoVG the errors will be there so I'd suggest just commenting out the offending lines of code.

**Pull request merged**
