### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ayazerzurum2**
Fixed version of the README.md file.

### CODE REVIEW

**Review by FelixFromDiscord — COMMENTED** [review]
While this PR has some good changes, it just switches british spellings to american ones :sob:

**Comment by TheKodeToad** [comment]
It's mostly better, but I'll merge it if you change the US spellings back.

**Comment by FelixFromDiscord** [comment]
> > It's mostly better, but I'll merge it if you change the US spellings back.
> 
> Sure, but why specifically? I don't see an actual reason.

because the owner IS BRITISH? :sob: :sob: :sob:

**Comment by TheKodeToad** [comment]
Thank you!

**Pull request merged**
