### PR TITLE
Added toggle sneak

### LINKED ISSUE #39: Toggle Sneak
Currently, this client is mainly focused on Hypixel, but many servers allow toggle sneak.

### PR DESCRIPTION
**Pull request by TatoExp**
I'm not sure where we get icons from/the process for icons for features.

I've done the en_US translations, but I'm also not sure of the process for other languages :)

Added by TheKodeToad: fixes #39.

### CODE REVIEW

**Comment by TatoExp** [comment]
I'm not sure why it included all those commits, I'm not sure if it makes a difference when looking at the diff.

**Comment by TheKodeToad** [comment]
Thanks again! Please can you add the author info?

```java
@Override
public String getCredit() {
	return I18n.format("sol_client.mod.screen.by", "<your name>");
}
```

Additionally I thought it could be possible to have toggle sprint and sneak as the same mod or at least *somehow* make them share a HUD. If this sounds confusing I can try implementing it.

As for the icons, they're just bad ones I made in Inkscape.

**Comment by RaptaG** [comment]
Will this be merged for the next release?

**Comment by TheKodeToad** [comment]
If TatoExp finishes it, but they said they were quite busy currently.

**Comment by TheKodeToad** [comment]
For those confused, Potato most likely closed this due to being banned from the Discord server. Locked as future discussion should be on the issue (not relating to this ban, though).

**Pull request closed without merging**
