### PR TITLE
add Scrollable Tooltips

### LINKED ISSUE #74: Add scrollable tool tips

### PR DESCRIPTION
**Pull request by moehreag**
- icon missing (not made)

- closes #74 

- updated german translation

@TheKodeToad more or less my revenge for you helping me with the motion blur. Thanks again for that!

### CODE REVIEW

**Comment by TheKodeToad** [comment]
Sorry for the late response - I was away from my PC.
I cannot merge this immediately due to complications with the multiversion update.

**Comment by moehreag** [comment]
> 

Ok, if you need something changed just tell me and I'll do it as soon as possible.

**Comment by TheKodeToad** [comment]
You didn't need to close it, but if that's how you want to do things that's fine.

**Comment by moehreag** [comment]
If it was my repo I'd rather not have a PR hanging around that can't be merged.. (No, it won't require many changes as it already didn't doing this.. and yes, this was also my first time not using the Fabric/Quilt Ecosystem)

**Comment by TheKodeToad** [comment]
I think I'll just mark it as draft so it's clear that this hasn't been rejected or anything.

**Comment by TheKodeToad** [comment]
Due to it taking a long time, I've decided to delay multiversion. Looks like this can finally be merged!

**Pull request merged**
