### PR TITLE
Update de_DE.lang

### PR DESCRIPTION
**Pull request by Uarml**
I've changed only one thing. It's already well translated

### CODE REVIEW

**Comment by TheKodeToad** [comment]
There are possibly some missing translation keys from en_us though...

**Comment by Uarml** [comment]
I've now changed one big thing in the German translation.
There was written "ermöglichen" which means: make something possible.
But the right thing is "aktivieren" which means: enable.
But how i said it's already well translated.

**Comment by TheKodeToad** [comment]
I was refering to text added since the translation such as "sol_client.mod.sol_client.option.broadcastOnline". If this is all you want to do in this pr though, that's fine!

**Comment by Uarml** [comment]
> sol_client.mod.sol_client.option.broadcastOnline
Ok, i'll try to add this

**Comment by TheKodeToad** [comment]
That was an example, there are a lot more so you may not wish to.

**Comment by Uarml** [comment]
> That was an example, there are a lot more so you may not wish to.

I know I am currently adding the missing stuff.

**Comment by TheKodeToad** [comment]
Oh, thanks!

**Comment by Uarml** [comment]
There are things in the German translation which aren't in the English version.
What should i do?

**Comment by TheKodeToad** [comment]
Delete them I guess...
I wonder why they are present.

**Comment by Uarml** [comment]
ok

**Comment by Uarml** [comment]
I've now added the missing stuff.

**Comment by TheKodeToad** [comment]
I can't review it, have you checked them?

**Comment by Uarml** [comment]
> I can't review it, have you checked them?

Checked what?

**Comment by TheKodeToad** [comment]
The added translations. Thanks for this btw!

**Comment by Uarml** [comment]
> 

Yes.
My Translation isn't the best. But for a little project like this. It's good enough.

**Pull request merged**
